Make work on Rocky9 and Ubuntu 22.04
ome/ansible-role-omero-server pull request #69
Opened 2023-10-02 11:03 UTC by pwalczysko

cc @jburel

2023-10-02 11:34 UTC, pwalczysko commented
Atm both Rocky9 and U22.04 are failing because of

```
   RUNNING HANDLER [ansible-role-omero-server : omero-server restart omero-server] ***
  fatal: [omero-server-rockylinux9]: FAILED! => {"changed": false, "msg": "Unable to start service omero-server: Job for omero-server.service failed because the control process exited with error code.\nSee \"systemctl status omero-server.service\" and \"journalctl -xeu omero-server.service\" for details.\n"}
```

I think that this is because of the unfinished dependency of the ``ome.ice`` dependency (?) 

cc @khaledk2 @sbesson

2023-10-02 14:50 UTC, sbesson commented
> I think that this is because of the unfinished dependency of the ome.ice dependency (?)

That's very possible but the error message is highly unspecific about the underlying error. To appreciate it fully, you would need to run `molecule converge` against  a local Docker container and shell into this container to look at the output of the commands.

2023-10-04 16:30 UTC, pwalczysko commented
```
 Ubuntu 22.04:
  
 CRITICAL Idempotence test failed because of the following tasks:
  *  => deploy_archive : deploy archive | unarchive
  *  => deploy_archive : deploy archive | unarchive
```
It could possibly be that the ^^^ failure of the idempotence on Ubuntu 22.04 is caused by me adding https://github.com/ome/ansible-role-omero-server/pull/69/commits/761f3e03bad0d426e05fee42eb230261c0dc577d - but, strangely, the idempotence passes on Rocky9 test. Any ideas about this @sbesson please ? I can see some hints in https://github.com/ome/ansible-role-omero-server/blob/cb5545b797bc8cef8428b1697d38a0b8b1bc23fc/molecule/ubuntu2004/molecule.yml#L26 but not sure what does that mean ?

2023-10-04 20:19 UTC, sbesson commented
> Any ideas about this @sbesson please ?

Nothing immediately, it comes a bit as a surprise that the idempotence would fail for one platform but not the other.
Part of the issue is that you are integrating N development branches and there are really a lot of moving targets to make an informed guess on the source of the issue. Is there a way to enable more logging to highlight why the task is being marked as changed?

2023-10-25 18:53 UTC, pwalczysko commented
The source of the failure of the idempotence seems to be the variable ``deploy_archive_filename`` from the deploy_archive role. It seems that the Ubuntu-22.04 test is attempting to unarchive the ...rhel9... tar.gz. But this is not something which succeeds imho, otherwise the ``converge`` test would fail, which it does not - the server is restarting happily on Ubuntu-22.04 according to the logs.

The problem is the value of that variable at the moment of the deploy archive task - see the logs below when a debug bit is added. Maybe the variable is not getting flushed - it seems like the ubuntu-22.04 test is alternately deploying the ...rhel9...tar.gz and ...ubuntu...tar.gz. 

This must be something to do with how these vars are used from the particular deploy archive and ice roles ? But unfortunately, do not see through this, any ideas please @khaledk2 @sbesson ?


```
2023-10-25T17:58:00.7657150Z TASK [deploy_archive : deploy archive | unarchive] *****************************
2023-10-25T17:58:08.5381043Z changed: [omero-server-rockylinux9]
2023-10-25T17:58:08.5477544Z 
2023-10-25T17:58:08.5478721Z TASK [deploy_archive : debug | unarchive] **************************************
2023-10-25T17:58:08.5928837Z ok: [omero-server-rockylinux9] => {
2023-10-25T17:58:08.5930284Z     "msg": "Orig path /opt/Ice-3.6.5-rhel9-x86_64.tar.gz dest path 172.17.0.1"
2023-10-25T17:58:08.5931339Z }
```

2023-10-25 19:03 UTC, pwalczysko commented
Sorry, edited ^^^ https://github.com/ome/ansible-role-omero-server/pull/69#issuecomment-1779864974 as the output of the log was confusing - now it really shows the ubuntu2204 weirdness

2023-10-25 20:58 UTC, sbesson commented
After some research, I believe you are hitting the issue described in the Note of https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#running-role-dependencies-multiple-times-in-one-play i.e. `Using vars: results in those variables being scoped at the play level`.

So [these variables](https://github.com/khaledk2/ansible-role-ice/blob/f4c8d6f658bd98801ca6f69f4c8b59c4329fe875/meta/main.yml#L48-L56) are scoped at the play level and are consumed in the initial invocation of the `ome.deploy_archive` role caused by the addition to the role dependencies. This possibly points out to a refactoring of the `ansible-role-ice` to move away from this logic. 

Re https://github.com/ome/ansible-role-omero-server/commit/761f3e03bad0d426e05fee42eb230261c0dc577d, is it not possible to add the deploy_archive to the `requirements.yml` only to ensure you are using the branch of interest? It is possible you are starting to reach the limit of testing nested dependencies.

As a final point, the CI builds really need to be reactivated for each PR across all these roles to simplify the reviewing.

2023-10-27 20:20 UTC, khaledk2 commented
I have figured out why it failed in `Ubuntu 22.04`. It called the `deploy_archive` role two times, the first one with the `REHL` ice package regardless of the platform (`Ubuntu` and `RockyLinux`).  The second call runs with the correct ice package for each platform. 

In this scenario, `Rockylinux` passed because it called the role twice with the same package (`REHL`) so it will change at the first call only, but for `Ubuntu`, it will be called two times with two different args so it will change in the second call also.

I have deleted the role inside the  [meta/main.yml](https://github.com/khaledk2/ansible-role-omero-server/blob/01416c572d58fce906d6aadec9d035895e58a40f/meta/main.yml#L21C1-L21C27) file which I think calls the `deploy_archive ` role with `REHL` ice only and this fixes the issue.
I have tested it in my fork and it is green now for both `Ubuntu` and `Rockylinux` after applying these changes.

https://github.com/khaledk2/ansible-role-omero-server/actions/runs/6671567723

2023-10-30 10:19 UTC, pwalczysko commented
> I have figured out why it failed in `Ubuntu 22.04`. It called the `deploy_archive` role two times, the first one with the `REHL` ice package regardless of the platform (`Ubuntu` and `RockyLinux`). The second call runs with the correct ice package for each platform.
> 
> In this scenario, `Rockylinux` passed because it called the role twice with the same correct package (`REHL`) so it will change at the first call only, but for `Ubuntu`, it will be called two times with two different args so it will change in the second call also.
> 
> I have commented out the role inside the [meta/main.yml](https://github.com/khaledk2/ansible-role-omero-server/blob/01416c572d58fce906d6aadec9d035895e58a40f/meta/main.yml#L21C1-L21C27) file which I think calls the `deploy_archive ` role with `REHL` ice only and this fixes the issue. I have tested it in my fork and it is green now for both `Ubuntu` and `Rockylinux` after applying these changes.
> 
> https://github.com/khaledk2/ansible-role-omero-server/actions/runs/6671567723

Amazing, thank you @khaledk2 - I have cherry-picked https://github.com/ome/ansible-role-omero-server/pull/69/commits/94c43cddb102d25eab6b987770827d7664d36387 and it makes the U22.04 test green here too !

thanks @sbesson and @khaledk2 for the help

2023-10-30 10:37 UTC, pwalczysko commented
I have run the playbook with the changes here also against the RHEL 9 testing system (although not on a clean image). The test passed.

2023-10-30 11:11 UTC, sbesson requested changes
Overall looks good. One suggestion about the service file and the PSQL versions.

Interesting to see that the role changes here are minimal and most of the required changes are in the role dependencies. As for all other RHEL9/Ubuntu22.04 PR, this also means we'll need a chain of releases and a last commit dropping links to the branches before giving this a final review

2023-10-30 12:06 UTC, pwalczysko commented on templates/systemd-system-omero-server-service.j2
> +After=postgresql-13.service
> Possibly worth starting listing all intermediate versions of PostgreSQL (and remove the outdated ones) as we don't know which PSQL service will be installed?

Thank you. I took my lead from https://github.com/ome/ansible-role-postgresql/pull/34/files#diff-663391f3716a8f003f6b83f6478f08fef0ad6e9266b29704b1ae547e70736f2cR59 and produced a new list in https://github.com/ome/ansible-role-omero-server/pull/69/commits/2ff3ef24e56606c859cf49859d9c8a11280b7705

2023-10-30 13:44 UTC, sbesson commented on templates/systemd-system-omero-server-service.j2
> +After=postgresql-13.service
:+1: I think this matches https://endoflife.date/postgresql. Arguably, you could add PSQL 15 to this list which has now been released 1 year ago

2023-10-30 15:00 UTC, sbesson approved these changes

2023-11-03 16:54 UTC, pwalczysko commented
The last two commits should be pointing this role to ome namespace in galaxy for all dependency roles.

But I am failing on a dependency variable declaration

```
   
  TASK [ansible-role-omero-server : omero server | create system user] ***********
  fatal: [omero-server-ubuntu2204]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ omero_common_basedir }}/server: 'omero_common_basedir' is undefined\n\nThe error appears to be in '/home/runner/work/ansible-role-omero-server/ansible-role-omero-server/tasks/omero-user.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: omero server | create system user\n  ^ here\n"}
```

2023-11-04 01:10 UTC, pwalczysko commented
The test is now green here. Also I was able to publish in galaxy as https://galaxy.ansible.com/ui/standalone/roles/pwalczysko/omero_server/   (pwalczysko.omero_server).

I will test tomorrow this role in playbook.

2023-11-04 09:15 UTC, khaledk2 commented
> The last two commits should be pointing this role to ome namespace in galaxy for all dependency roles.
> 
> But I am failing on a dependency variable declaration
> 
> ```
>    
>   TASK [ansible-role-omero-server : omero server | create system user] ***********
>   fatal: [omero-server-ubuntu2204]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ omero_common_basedir }}/server: 'omero_common_basedir' is undefined\n\nThe error appears to be in '/home/runner/work/ansible-role-omero-server/ansible-role-omero-server/tasks/omero-user.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: omero server | create system user\n  ^ here\n"}
> ```

I have a similar issue in the `omero-web` role, I fixed it by using `import_role` for the `ome.omero_common` role instead of `include_role `inside `pre_tasks.yml`.

I think you should use this approach rather than hardcode the variable.

2023-11-04 16:22 UTC, pwalczysko commented
Tested this role in playbook, see https://github.com/ome/ansible-role-omero-web/pull/48#issuecomment-1793487604 - works as expected.

2023-11-09 11:07 UTC, jburel commented on templates/systemd-system-omero-server-service.j2
> +After=postgresql-13.service
psql 11 is ending today 09/11 so we should probably remove it from the list

2023-11-10 13:02 UTC, pwalczysko commented on molecule/rockylinux9/molecule.yml
> +      - /tmp
fixed in https://github.com/ome/ansible-role-omero-server/pull/69/commits/570833b710f7781479f311b21dea9bd829e3484c

2023-11-10 13:03 UTC, pwalczysko commented
The comments of @khaledk2 were adressed. The python bumped to 3.9. The build is green and there are no errors&warnings on GA.

cc @jburel @khaledk2

2023-11-13 11:18 UTC, pwalczysko commented
Do we want to merge&release this in order to enable the deployment of the server please ?

2023-11-13 12:09 UTC, pwalczysko commented on templates/systemd-system-omero-server-service.j2
> +After=postgresql-15.service
fixed in https://github.com/ome/ansible-role-omero-server/pull/69/commits/9c844c58f0c6224782359ff2c394fa4cbdf18f65

2023-11-13 13:49 UTC, merged